server:
  port: 8762
spring:
  application:
    name: shop-member
  redis:
    host: 192.168.21.130
    password: root
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    name: test
#    password: root
#    url: jdbc://mysql://127.0.0.1:3306/shop-member
#    username: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMills: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#  activemq:
#    broker-url: tcp://localhost:61616
#    in-memory: true
#    pool:
#      enabled: false

#messages:
#  queue: messages_queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
